permissions:
  contents: write
  
name: Build ReDoc and publish to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      # 👇 Export the OpenAPI YAML dynamically
      - name: Export OpenAPI spec
        run: python scripts/export_openapi.py

      - name: Install Redocly CLI
        run: npm install -g @redocly/cli

      - name: Generate ReDoc HTML
        run: npx @redocly/cli build-docs openapi.yaml -o docs/index.html

      - name: Add .nojekyll
        run: touch docs/.nojekyll

      - name: Commit & push docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/index.html docs/.nojekyll
          git commit -m "Auto-generate ReDoc docs [skip ci]" || echo "No changes to commit"
          git push